include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "bin/**"
    - "goo2d_lints/**"

linter:
  rules:
    - public_member_api_docs
    - slash_for_doc_comments

formatter: 
  trailing_commas: preserve