include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "bin/**"
    - "goo2d_lints/**"

linter:
  rules:
    - public_member_api_docs
    - slash_for_doc_comments
    - always_use_package_imports # for the sake of import consistency

formatter: 
  trailing_commas: preserve