name: goo2d
description: "A Low Level 2D Game Engine for Flutter"
version: 0.0.1
homepage: https://sunarya-thito.github.io/goo2d/
repository: https://github.com/sunarya-thito/goo2d
issues: https://github.com/sunarya-thito/goo2d/issues
publish_to: 'pub.dev'

environment:
  sdk: ^3.11.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_soloud: ^4.0.3
  http: ^1.6.0
  meta: ^1.17.0
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  benchmark_harness: ^2.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

topics:
  - game-engine
  - 2d
  - game
  - ecs