name: goo2d_lints
description: Custom lint rules for the Goo2D game engine.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.11.4

dependencies:
  analyzer: ^7.2.0
  custom_lint_builder: ^0.7.0
