import 'dart:math' as math;
import 'package:vector_math/vector_math_64.dart';

/// A contact point generated by narrowphase detection.
class ContactManifold {
  final Vector2 normal;
  final List<ContactVertex> contacts;

  const ContactManifold(this.normal, this.contacts);
}

class ContactVertex {
  final Vector2 point;
  final double penetration;

  const ContactVertex(this.point, this.penetration);
}

/// Circle vs Circle.
ContactManifold? circleVsCircle(
    Vector2 c1, double r1, Vector2 c2, double r2) {
  final d = c2 - c1;
  final distSq = d.length2;
  final totalR = r1 + r2;
  if (distSq > totalR * totalR) return null;

  final dist = math.sqrt(distSq);
  final normal = dist > 1e-10 ? d / dist : Vector2(1, 0);
  final penetration = totalR - dist;
  final point = c1 + normal * (r1 - penetration * 0.5);
  return ContactManifold(normal, [ContactVertex(point, penetration)]);
}

/// Circle vs polygon (convex, world-space vertices, wound CCW).
ContactManifold? circleVsPolygon(
    Vector2 circleCenter, double radius,
    List<Vector2> vertices) {
  if (vertices.length < 3) return null;

  // Find the closest edge/vertex
  var minDist = double.maxFinite;
  var bestNormal = Vector2.zero();
  var bestPoint = Vector2.zero();

  for (var i = 0; i < vertices.length; i++) {
    final j = (i + 1) % vertices.length;
    final v1 = vertices[i];
    final v2 = vertices[j];
    final edge = v2 - v1;
    final edgeLen = edge.length;
    if (edgeLen < 1e-10) continue;

    final edgeDir = edge / edgeLen;
    final toCircle = circleCenter - v1;
    var t = toCircle.dot(edgeDir);
    t = t.clamp(0, edgeLen);

    final closest = v1 + edgeDir * t;
    final diff = circleCenter - closest;
    final dist = diff.length;

    if (dist < minDist) {
      minDist = dist;
      bestPoint = closest;
      bestNormal = dist > 1e-10 ? diff / dist : _edgeNormal(v1, v2);
    }
  }

  if (minDist > radius) return null;

  final penetration = radius - minDist;
  return ContactManifold(
    -bestNormal, // Points from polygon toward circle
    [ContactVertex(bestPoint, penetration)],
  );
}

Vector2 _edgeNormal(Vector2 a, Vector2 b) {
  final e = b - a;
  return Vector2(-e.y, e.x)..normalize();
}

/// Polygon vs Polygon using SAT (Separating Axis Theorem).
ContactManifold? polygonVsPolygon(
    List<Vector2> vertsA, List<Vector2> vertsB) {
  if (vertsA.length < 3 || vertsB.length < 3) return null;

  final result = _satTest(vertsA, vertsB);
  if (result == null) return null;

  return _buildPolygonContacts(vertsA, vertsB, result);
}

/// SAT overlap result.
class _SATResult {
  final Vector2 axis;
  final double depth;
  final bool fromA;
  final int edgeIndex;
  const _SATResult(this.axis, this.depth, this.fromA, this.edgeIndex);
}

_SATResult? _satTest(List<Vector2> a, List<Vector2> b) {
  double minOverlap = double.maxFinite;
  Vector2 bestAxis = Vector2.zero();
  bool fromA = true;
  int bestEdge = 0;

  // Test edges of A
  for (var i = 0; i < a.length; i++) {
    final j = (i + 1) % a.length;
    final edge = a[j] - a[i];
    final normal = Vector2(-edge.y, edge.x)..normalize();

    final projA = _projectPolygon(a, normal);
    final projB = _projectPolygon(b, normal);
    final overlap = _overlapAmount(projA, projB);
    if (overlap <= 0) return null;

    if (overlap < minOverlap) {
      minOverlap = overlap;
      bestAxis = normal;
      fromA = true;
      bestEdge = i;
    }
  }

  // Test edges of B
  for (var i = 0; i < b.length; i++) {
    final j = (i + 1) % b.length;
    final edge = b[j] - b[i];
    final normal = Vector2(-edge.y, edge.x)..normalize();

    final projA = _projectPolygon(a, normal);
    final projB = _projectPolygon(b, normal);
    final overlap = _overlapAmount(projA, projB);
    if (overlap <= 0) return null;

    if (overlap < minOverlap) {
      minOverlap = overlap;
      bestAxis = normal;
      fromA = false;
      bestEdge = i;
    }
  }

  // Ensure normal points from A to B
  final centerA = _polygonCenter(a);
  final centerB = _polygonCenter(b);
  if (bestAxis.dot(centerB - centerA) < 0) {
    bestAxis = -bestAxis;
  }

  return _SATResult(bestAxis, minOverlap, fromA, bestEdge);
}

(double, double) _projectPolygon(List<Vector2> verts, Vector2 axis) {
  var min = verts[0].dot(axis);
  var max = min;
  for (var i = 1; i < verts.length; i++) {
    final d = verts[i].dot(axis);
    if (d < min) min = d;
    if (d > max) max = d;
  }
  return (min, max);
}

double _overlapAmount((double, double) a, (double, double) b) {
  return math.min(a.$2, b.$2) - math.max(a.$1, b.$1);
}

Vector2 _polygonCenter(List<Vector2> verts) {
  var cx = 0.0, cy = 0.0;
  for (final v in verts) { cx += v.x; cy += v.y; }
  return Vector2(cx / verts.length, cy / verts.length);
}

ContactManifold _buildPolygonContacts(
    List<Vector2> vertsA, List<Vector2> vertsB, _SATResult sat) {
  // Use edge clipping to find contact points
  final ref = sat.fromA ? vertsA : vertsB;
  final inc = sat.fromA ? vertsB : vertsA;
  final refIdx = sat.edgeIndex;

  final v1 = ref[refIdx];
  final v2 = ref[(refIdx + 1) % ref.length];
  final refEdge = (v2 - v1)..normalize();
  final refNormal = sat.axis;

  // Find incident edge on the other polygon
  final incEdge = _findIncidentEdge(inc, -refNormal);
  final i1 = inc[incEdge];
  final i2 = inc[(incEdge + 1) % inc.length];

  // Clip incident edge against reference edge side planes
  var clipped = [i1, i2];
  clipped = _clipSegment(clipped, refEdge, refEdge.dot(v1));
  if (clipped.length < 2) return ContactManifold(refNormal, []);
  clipped = _clipSegment(clipped, -refEdge, -refEdge.dot(v2));
  if (clipped.length < 2) return ContactManifold(refNormal, []);

  // Keep only points behind the reference face
  final refD = refNormal.dot(v1);
  final contacts = <ContactVertex>[];
  for (final cp in clipped) {
    final sep = refNormal.dot(cp) - refD;
    if (sep <= 0) {
      contacts.add(ContactVertex(cp, -sep));
    }
  }

  return ContactManifold(refNormal, contacts);
}

int _findIncidentEdge(List<Vector2> verts, Vector2 normal) {
  var bestDot = double.maxFinite;
  var bestIdx = 0;
  for (var i = 0; i < verts.length; i++) {
    final j = (i + 1) % verts.length;
    final edge = verts[j] - verts[i];
    final n = Vector2(-edge.y, edge.x)..normalize();
    final d = n.dot(normal);
    if (d < bestDot) { bestDot = d; bestIdx = i; }
  }
  return bestIdx;
}

List<Vector2> _clipSegment(List<Vector2> points, Vector2 normal, double offset) {
  final result = <Vector2>[];
  final d0 = normal.dot(points[0]) - offset;
  final d1 = normal.dot(points[1]) - offset;

  if (d0 >= 0) result.add(points[0]);
  if (d1 >= 0) result.add(points[1]);

  if (d0 * d1 < 0) {
    final t = d0 / (d0 - d1);
    result.add(points[0] + (points[1] - points[0]) * t);
  }
  return result;
}
